### ISSUE TITLE
Create password for databases and store them in Vault

### ISSUE THREAD

**Issue by MattesR** [liquidinvestigations/node#61]
Right now, our databases do not have passwords. We should make use of Vault and generate + store secrets for our databases in Vault.

see also: https://github.com/CRJI/EIC/issues/219

**Comment by mgax** [comment]
Here are the manual steps I had to run in order to migrate the hoover database from `hoover` (username, password, and database name) to `search` (all 3):

```
root@7af2768730be:/# createuser -U hoover -s postgres
root@7af2768730be:/# psql -U postgres
postgres=# alter role hoover rename to search
postgres=# alter database hoover rename to search
```

Interestingly, it said `NOTICE:  MD5 password cleared because of role rename` after renaming the user, so I guess I removed its password entirely.
